/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aleatorios;

import com.sun.org.apache.xerces.internal.impl.dtd.models.CMAny;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javazoom.jlgui.basicplayer.BasicPlayer;

/**
 *
 * @author vbarrera
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    Thread hilo;
    boolean estado;
    int ranm[];
    int gana;
    int alea;
    Vector numeros;
    Image icon;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm");
    ConexionMysql cm = new ConexionMysql();
    String dato;
    String resultado;
    Thread tInicio;
    int numeroDeJugadores;
    
    public Ventana() {
        
        initComponents();
        icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/favicon.png"));
        setIconImage(icon);
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        selecionar.setEnabled(false);
        selecionar.setVisible(false);
        detener.setVisible(false);
        inicio();
        
        estado = false;
    }
    
    public void ale() {
        cm.conectar();
        
        hilo = new Thread(new Runnable() {
            
            Random rnd = new Random();
            
            @Override
            public void run() {
                ResultSet cont = cm.Consultar("SELECT count(*) as num FROM fecha_maquina WHERE fecha = '" + resultado + "' ");
                try {
                    if (cont.next()) {
                        
                        numeroDeJugadores = cont.getInt("num");
                        System.out.println("Numero " + cont.getInt("num"));
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
                }
                ranm = new int[numeroDeJugadores];
                
                ResultSet rs = cm.Consultar("SELECT maquina FROM fecha_maquina WHERE fecha = '" + resultado + "' ");
                try {
                    int n = 0;
                    while (rs.next()) {
                        
                        
                            ranm [n]= rs.getInt("maquina");
                       n+=1;
                        System.out.println(" maquina " + rs.getInt("maquina"));
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
                }
                alea = rnd.nextInt(numeroDeJugadores);
              
                    
                   // System.err.println("Ma "+s);
               
//                for (int i = 0; i < numeroDeJugadores; i++) {
//                    alea = rnd.nextInt(numeroDeJugadores);
                    try {
                        Thread.sleep(50);
                        
//                        alea = rnd.nextInt(220);
                        //if (gana != alea) {
                       
                          numero.setText("" + ranm[alea]);
                           ganador.setText(""+ranm[alea]);
                        
                        
                            //numero.setText("");
                        //  }

                    } catch (InterruptedException ex) {
                        Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
            
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoGanador = new javax.swing.JDialog();
        jpanelGanador = new javax.swing.JPanel();
        ganagana = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        detener = new javax.swing.JToggleButton();
        numero = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selecionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        ganador = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        dialogoGanador.setTitle("Ganador");

        jpanelGanador.setDoubleBuffered(false);
        jpanelGanador.setFocusable(false);
        jpanelGanador.setOpaque(false);
        jpanelGanador.setRequestFocusEnabled(false);
        jpanelGanador.setVerifyInputWhenFocusTarget(false);

        ganagana.setFont(new java.awt.Font("Britannic Bold", 1, 36)); // NOI18N
        ganagana.setForeground(new java.awt.Color(153, 0, 153));
        ganagana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ganagana.setText(" ");

        javax.swing.GroupLayout jpanelGanadorLayout = new javax.swing.GroupLayout(jpanelGanador);
        jpanelGanador.setLayout(jpanelGanadorLayout);
        jpanelGanadorLayout.setHorizontalGroup(
            jpanelGanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelGanadorLayout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(ganagana, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jpanelGanadorLayout.setVerticalGroup(
            jpanelGanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelGanadorLayout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(ganagana, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout dialogoGanadorLayout = new javax.swing.GroupLayout(dialogoGanador.getContentPane());
        dialogoGanador.getContentPane().setLayout(dialogoGanadorLayout);
        dialogoGanadorLayout.setHorizontalGroup(
            dialogoGanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoGanadorLayout.createSequentialGroup()
                .addComponent(jpanelGanador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        dialogoGanadorLayout.setVerticalGroup(
            dialogoGanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoGanadorLayout.createSequentialGroup()
                .addComponent(jpanelGanador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generación Aleatoria Máquina");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.red);
        setIconImages(null);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        detener.setBackground(new java.awt.Color(204, 204, 0));
        detener.setFont(new java.awt.Font("Batang", 0, 11)); // NOI18N
        detener.setText("Generar Número");
        detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detenerActionPerformed(evt);
            }
        });

        numero.setFont(new java.awt.Font("Batang", 0, 100)); // NOI18N
        numero.setForeground(new java.awt.Color(255, 255, 255));
        numero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Batang", 1, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("No. Máquina Seleccionada");

        selecionar.setFont(new java.awt.Font("Batang", 0, 11)); // NOI18N
        selecionar.setText("Seleccionar");
        selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nao.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nao.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)
                        .addGap(219, 219, 219)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(detener, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addGap(41, 41, 41)
                                .addComponent(selecionar, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(217, 217, 217)
                        .addComponent(jLabel5)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(detener, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setToolTipText("");

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setEnabled(false);
        jScrollPane2.setFocusable(false);
        jScrollPane2.setWheelScrollingEnabled(false);

        area.setEditable(false);
        area.setBackground(new java.awt.Color(0, 51, 102));
        area.setColumns(5);
        area.setFont(new java.awt.Font("Batang", 0, 80)); // NOI18N
        area.setForeground(new java.awt.Color(255, 255, 255));
        area.setLineWrap(true);
        area.setRows(5);
        area.setWrapStyleWord(true);
        area.setAutoscrolls(false);
        area.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        area.setFocusable(false);
        area.setRequestFocusEnabled(false);
        area.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(area);

        ganador.setFont(new java.awt.Font("Batang", 1, 50)); // NOI18N
        ganador.setForeground(new java.awt.Color(255, 255, 255));
        ganador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ganador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel3.setFont(new java.awt.Font("Batang", 1, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("# Ganadores");

        jLabel4.setFont(new java.awt.Font("Batang", 1, 50)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Máquina Ganadora");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1001, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel3)
                    .addContainerGap(355, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void inicio() {
        
        tInicio = new Thread(new Runnable() {
            
            @Override
            public void run() {
                cm.conectar();
                while (true) {
                    try {
                        Thread.sleep(1000);
                        Date fecha = new Date();
                        dato = sdf.format(fecha);
                        ResultSet resl = cm.Consultar("SELECT fecha FROM fecha_maquina WHERE fecha=\"" + dato + "\"");
                        while (resl.next()) {
                            resultado = sdf.format(resl.getTimestamp("fecha"));
                            System.err.println("" + dato + " " + resultado);
                            
                        }
                        if (dato.equals(resultado)) {
                            // JOptionPane.showMessageDialog(null, "Corriendo");
                            System.out.println("Prueba");
                            ale();
                            hilo.start();
                            
                        }
                        System.err.println("R " + resultado);
                        
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    // cm.desconectar();
                }
                
            }
        });
        tInicio.start();
    }
    private void detenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detenerActionPerformed
        if (detener.isSelected()) {
            if (!estado) {
                
                hilo.start();

                // hilo.stop();
            } else {
                hilo.resume();
                estado = false;
                detener.setText("Detener");
                selecionar.setEnabled(false);
                
            }
        } else {
            detener.setText("Continuar");
            selecionar.setEnabled(true);
            hilo.suspend();
            area.append(" \n" + alea);
            estado = true;
        }
        

    }//GEN-LAST:event_detenerActionPerformed

    private void selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarActionPerformed
        Panel p = new Panel("/imagenes/Ganador.jpg");
        jpanelGanador.add(p);
        dialogoGanador.setVisible(true);
        dialogoGanador.setSize(508, 408);
        dialogoGanador.setMaximumSize(new Dimension(getWidth(), getHeight()));
        dialogoGanador.setIconImage(icon);
        dialogoGanador.setLocationRelativeTo(null);
        ganador.setText("" + numero.getText());
        ganagana.setText("" + numero.getText());
        
        reproduciraudio("C:/musica/Aplausos.mp3");
        

    }//GEN-LAST:event_selecionarActionPerformed
    public void reproduciraudio(String file) {
        
        try {
            
            BasicPlayer sonido = new BasicPlayer();
            
            sonido.open(new File(file));
            
            sonido.play();
            
        } catch (Exception e) {
            
            System.out.println(e);
            
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JToggleButton detener;
    private javax.swing.JDialog dialogoGanador;
    private javax.swing.JLabel ganador;
    private javax.swing.JLabel ganagana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpanelGanador;
    private javax.swing.JLabel numero;
    private javax.swing.JButton selecionar;
    // End of variables declaration//GEN-END:variables
}
